name = "astro-visits"
main = ".astro/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "wilddb"
database_id = "55d3f8f9-29f4-4516-8752-b8000e481a33"

[[d1_databases]]
binding = "VISITS_DB"
database_name = "visits-db"
database_id = "your-database-id-here"
